# Site settings
title: Gallery
description: these are some cool pictures I've taken over the years.  Enjoy!
baseurl: "/gala" # the subpath of your site, e.g. /blog
url: "//geande.github.io" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url: https:://github.com/geande
instagram_url: https://www.instagram.com/atgarrett52/
linkedin_url: https://www.linkedin.com/in/andrew-garrett-939a94143/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
